version: 0.7
index_id: siem-alerts
doc_mapping:
  mode: dynamic
  field_mappings:
    - name: alert_type
      type: text
      tokenizer: default
      fast: true
    - name: severity
      type: text
      tokenizer: default
      fast: true
    - name: source_ip
      type: text
      tokenizer: default
      fast: true
    - name: event_count
      type: u64
      fast: true
    - name: timestamp
      type: datetime
      input_formats: ["unix_timestamp"]
      fast: true